### ISSUE TITLE
scroll direction is backwards

### ISSUE THREAD

**Issue by DeedleFake** [wojciech-graj/OrbVis#2]
Every other app I've ever used uses scrolling _up_ to zoom in and down to zoom out, but this reverses that. It's very confusing. If you really want the scrolling to be that direction, could you at least add an option to change it, please?

**Comment by wojciech-graj** [comment]
Fair enough. I did a lot of the program's development on a laptop instead of my usual PC, so I just guessed how the scrolling should work. I'll change this within the next couple of days.

**Comment by wojciech-graj** [comment]
Fixed in commit [86dfcaf](https://github.com/wojciech-graj/OrbVis/commit/86dfcaffa3c928a60474f2b9f46c204400229ef9). Thank you for bringing this to my attention.
