### ISSUE TITLE
Setting to change satellite size

### ISSUE THREAD

**Issue by ashrude** [wojciech-graj/OrbVis#3]
satellites are a bit hard to see. It would be nice for there to be a setting to change the particle size

**Comment by wojciech-graj** [comment]
Oh geez, it's time to dig around in my shaders that I haven't touched for almost a year. I'll try to get around to implementing this sometime this week

**Comment by wojciech-graj** [comment]
Fixed in commit 1cba834. Thanks for bringing this to my attention!
